### ISSUE TITLE
Add more checks for metadata contents

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator-app#11]
Check values that correspond to annotations and provide feedback about invalid values (and where to find the correct ones)

**Comment by larssono** [comment]
Do you already have decided on how the location and values of correct ones will be referenced?  I.e. how will these be defined outside of the code.

**Comment by karawoo** [comment]
I was planning to use what's defined in https://github.com/Sage-Bionetworks/synapseAnnotations

This is already what we use for validating the file annotations, so it's just a matter of applying the same checks to the contents of the files themselves. However, it's possible we'd want to add additional requirements beyond what's used for annotations. Where/how to store that hasn't yet been discussed or decided.
