### ISSUE TITLE
Clean up uploaded files when session ends

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator-app#2]
Otherwise they will hang around on the server. 
* [More info](https://groups.google.com/d/msg/shiny-discuss/fHshZgc0yJg/DyDKMmnUyG8J)
* [Sample code to remove files on session end](https://groups.google.com/d/msg/shiny-discuss/2WSKDO3Rljo/1syiNLecFeYJ)

**Comment by larssono** [comment]
is it possible to create temporary files that delete themselves?  In Python, depending on which type of tmp file you create they either hang around or get deleted when you close the file pointer.

**Comment by karawoo** [comment]
This is already implemented by shiny (after the links above were written): 
https://github.com/rstudio/shiny/blob/c332c051f33fe325f6c2e75426daaabb6366d50a/R/fileupload.R#L129-L138
